"""empty message

Revision ID: 3bd043323208
Revises: d9efa93ec065
Create Date: 2020-07-14 01:51:38.022511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd043323208'
down_revision = 'd9efa93ec065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_image_link', sa.String(), nullable=False))
    op.add_column('Show', sa.Column('artist_name', sa.String(length=120), nullable=False))
    op.add_column('Show', sa.Column('venue_name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_name')
    op.drop_column('Show', 'artist_name')
    op.drop_column('Show', 'venue_image_link')
    # ### end Alembic commands ###
