"""empty message

Revision ID: 79e081bd8c35
Revises: 239e45894663
Create Date: 2020-07-14 07:07:21.862498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e081bd8c35'
down_revision = '239e45894663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_image_link', sa.String(length=120), nullable=False))
    op.drop_column('Show', 'artist_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_image_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'venue_image_link')
    # ### end Alembic commands ###
