"""empty message

Revision ID: b41006906dbe
Revises: 79e081bd8c35
Create Date: 2020-07-14 07:10:41.903465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41006906dbe'
down_revision = '79e081bd8c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_image_link', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
